---
- name: remove users from list
  hosts: localhost
  become: true
  vars_files:
    user_dict2.yml
  tasks:

    - user: 
        name: "{{ item.key }}"
        state: absent
      with_dict: "{{ users }}"
