---
- name: Remove users
  hosts: all
  become: true
  vars:
    users:
      - billy
      - joe
      - jim
      - bob
  tasks:
    - user: 
        name: "{{ item }}"
        state: absent
      loop: "{{ users }}"
